# NumPY
NumericalPy


Numpy is the core library for scientific computing in Python. 

It provides a high-performance multidimensional array object, and tools for working with these arrays. 

Similar to  MATLAB.


####  The Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

In [ ]:
### ndarray [ndimensional array]
## Atributes
n.dim, shape, dype,itemsize,data

![ndarray](ndarray.png)

Above figure shows the conceptual diagram showing the relationship between the three fundamental objects used to describe the data in an array: 

1) the ndarray itself, 

2) the data-type object that describes the layout of a single fixed-size element of the array, 

3) the array-scalar Python object that is returned when a single element of the array is accessed.


In [53]:
#a=np.array([1,2,3])
b=np.array([1,2,3,4])

print(b)

[1 2 3 4]


In [22]:
a=np.array({1,2,3})
print(a)

{1, 2, 3}


In [54]:
a=np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [55]:
a=np.array([[1,2,3],[3,4,5]]) ## corrected the syntax
print(a)

[[1 2 3]
 [3 4 5]]


In [56]:
print(a.shape)

(2, 3)


In [58]:
a=np.array([[1,"name",2.0],[4.0,2.0,1.0]])
print(a)
print(a.shape)

[['1' 'name' '2.0']
 ['4.0' '2.0' '1.0']]
(2, 3)


In [60]:
a=np.array([[1,"name",2.0],[4.0,2.0]])
print(a)
print(a.shape)

[list([1, 'name', 2.0]) list([4.0, 2.0])]
(2,)


### Create an array with default values

In [62]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
print(a.shape)

(10,)


In [64]:
a = np.zeros(5,2)
print(a)

TypeError: data type not understood

In [65]:
a = np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [66]:
print(a.shape)

(5, 3)


In [67]:
a=np.ones((3,2))
print(a)
print(a.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


In [69]:
a = np.full((2,2), "3")
print(a)
print("shape is ",a.shape)

[['3' '3']
 ['3' '3']]
shape is  (2, 2)


In [71]:
a = np.full((2,2), 4)
print(a)
print("shape is ",a.shape)

[[4 4]
 [4 4]]
shape is  (2, 2)


In [46]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)   
print("shape is ",d.shape)

[[1. 0.]
 [0. 1.]]
shape is  (2, 2)


In [72]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)   

[[1. 0.]
 [0. 1.]]


In [73]:
e = np.random.random((4,4))  # Create an array filled with random values
print(e)                     # 

[[0.76068335 0.58389729 0.15239451 0.57620734]
 [0.97233318 0.76881203 0.99790419 0.36821529]
 [0.71734922 0.97988529 0.96095958 0.80993452]
 [0.69823671 0.17197482 0.48857584 0.88793242]]


### Array indexing
Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [82]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows# and columns 1 and 2; b is the 
#following array of shape (2, 2):
#b = a[:2, 1:3]
print("b is ")
#print(b)

# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])   # Prints "2"
#b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0][1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b is 
2
2


#### If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [85]:
import numpy as np
print(np.arange(10000))
#print('\n')
print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# Sorting

In [90]:
# Python program to demonstrate sorting in numpy 
import numpy as np 
  
a = np.array([[1, 4, 2],  [3, 4, 6],[0, -1, 5]]) 
print(a)
  
# sorted array 
#print ("Array elements in sorted order:\n", np.sort(a, axis = None))  
#print ("Row-wise sorted array:\n", np.sort(a, axis = 1))  # sort row wise
  

#print ("Column wise sort by applying merge-sort:   \n", np.sort(a, axis = 0)) # specify sort algorithm 
print ("Column wise sort by applying merge-sort:   \n", np.sort(a, axis = 0, kind = 'mergesort'))


[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]
Column wise sort by applying merge-sort:   
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [93]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]  #Example to show sorting of structured array , set alias names for dtypes 
  
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
             
arr = np.array(values, dtype = dtypes) 
print(arr)
#print ("\nArray sorted by names:\n", np.sort(arr, order = 'name')) 
              
print ("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa'])) 


[(b'Hrithik', 2009, 8.5) (b'Ajay', 2008, 8.7) (b'Pankaj', 2008, 7.9)
 (b'Aakash', 2009, 9. )]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


# Array Concatenation and Splitting

####  Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack, and np.hstack. np.concatenate

In [94]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [95]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([grid,x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [96]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting 

####  The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [100]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
print(x)
x1, x2, x3 = np.split(x, [3, 2])
print(x1, x2, x3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [] [ 3 99 99  3  2  1]


In [47]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[9 8 7]
 [6 5 4]]
[]


### Copies and Views

In [104]:
a = np.arange(5)
print(a)
b = a            # no new object is created
#print(a)
print(b)
b is a         # a and b are two names for the same ndarray object


[0 1 2 3 4]
[0 1 2 3 4]


True

# Slicing

In [ ]:
### understanding slicing with one dimensional array

In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [5]:
print(a[:2])

[1 2]


In [10]:
print(a)
print(a[::1]) 
print(a[::2])
print(a[::3])
print(a[::4])
print(a[::5])
print(a[::6])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 4 7]
[1 5 9]
[1 6]
[1 7]


In [56]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
slice1 = a[:2]
print(slice1)

[[1 2 3 4]
 [5 6 7 8]]


In [63]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
slice1 = a[:2]
print(slice1)

[[1 2 3 4]
 [5 6 7 8]]


![Slicing](slice.jpg)

In [12]:
a=np.array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])

In [24]:
print(a[:,4])

[15 20 25 30 35]


In [106]:
print(a[::2])

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]


In [108]:
print(a[::2,::2])

[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [25]:
import numpy as np

x = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],
       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
print(x.shape)

(3, 3, 3)


In [11]:
print(x.sum(axis=2))

[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [26]:
x.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

# Integer array indexing: 

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Example:

In [31]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])  # An example of integer array indexing. # The returned array will have shape (3,) and
print("Intial array \n",a)
print("-----")
#print(a[[0,1,2]])
#print(a[[0, 1, 2], [0, 0, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"


#print(a[[0, 0], [1, 1]])  # When using integer array indexing, you can reuse the same
# element from the source array:
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

Intial array 
 [[1 2]
 [3 4]
 [5 6]]
-----
[1 3 5]
[1 4 5]
[2 2]
[2 2]


# Boolean Array Indexing

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [41]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
bool_index = (a>2)
print(bool_index)    ## returns True if element is > 2

[[False False]
 [ True  True]
 [ True  True]]


In [155]:
print(a[bool_index])

[3 4 5 6]


In [156]:
print(a[a > 2])   ## We can also the same with this statement

[3 4 5 6]


# Array Maths

In [43]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print("--------")
print(y)

[[1. 2.]
 [3. 4.]]
--------
[[5. 6.]
 [7. 8.]]


In [44]:
z = x+y
print(z)

[[ 6.  8.]
 [10. 12.]]


In [162]:
z=np.add(x,y)
print(z)

[[ 6.  8.]
 [10. 12.]]


In [164]:
y=np.subtract(x,y)
print(y)

[[-4. -4.]
 [-4. -4.]]


In [166]:
a=x-y
print(a)

[[5. 6.]
 [7. 8.]]


In [46]:
print(x)
print("----")
print(y)
print("----")
print(x*y)
print("----")
print(np.multiply(x,y))
print(" ******* Division**** ")
print(x/y)
print(np.divide(x,y))

[[1. 2.]
 [3. 4.]]
----
[[5. 6.]
 [7. 8.]]
----
[[ 5. 12.]
 [21. 32.]]
----
[[ 5. 12.]
 [21. 32.]]
 ******* Division**** 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [173]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Okay but how about matrix manipulations

In [ ]:
## multiple, additions etc are element by element operations



In [175]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("xxxxxxx")
print(x)
print("yyyyyyyy")
print(y)

xxxxxxx
[[1 2]
 [3 4]]
yyyyyyyy
[[5 6]
 [7 8]]


In [176]:
print(np.dot(x,y))  ## Dot product or matrix multiplication

[[19 22]
 [43 50]]


In [177]:
v = np.array([9,10])
w = np.array([11, 12])
print("v is \n")
print(v)
print("w is \n")
print(w)

v is 

[ 9 10]
w is 

[11 12]


In [180]:
print(v.dot(w))   ### Inner product of the vectors

### What is this value corresponding to ?

219


In [181]:
print(np.dot(v, w))

219


In [183]:
### Matrix multiplication

In [182]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [184]:
print(np.inner(x,y))

[[17 23]
 [39 53]]


In [187]:
x = np.array([[1,2],[3,4]])
print(x)

print(np.sum(x))  # Compute sum of all elements; prints "10"


[[1 2]
 [3 4]]
10


In [186]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"


[4 6]


In [188]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[3 7]


# reshaping the data


 Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [47]:
x = np.array([[1,2], [3,4],[4,5]])
print(x)
print(x.shape)

[[1 2]
 [3 4]
 [4 5]]
(3, 2)


In [192]:
y = x.T
print(y)
print(y.shape)

[[1 3]
 [2 4]]
(2, 2)


In [196]:
x = np.array([[1,2], [3,4],[5,6]])
print(x)
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [197]:
y = x.T
print(y)
print(y.shape)

[[1 3 5]
 [2 4 6]]
(2, 3)


In [48]:
#### Transposing a one dimensional array
x=np.array([1,2,3])
print(x)
y=x.T
print(y)

[1 2 3]
[1 2 3]


In [ ]:
### Transpose does nothing to a one dimensional array

### Mathematical functions at

https://docs.scipy.org/doc/numpy/reference/routines.math.html
    

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

# Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

#### Example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:
 We will add the vector v to each row of the matrix x,
storing the result in the matrix y

In [1]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [3]:
y = np.empty_like(x)   # Create an empty matrix with the same shape as x
print(y)

[[-4611686018427387904 -6917520244464277976                    6]
 [                   0           4294967296  3832119515839358315]
 [ 3258462328318211123  7148958827184076645  3975893635343396148]
 [ 3907217245652542309  8386112019185624373     1688854417077109]]


In [4]:

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
#This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. 
#Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv 
#by stacking multiple copies of v vertically, then performing elementwise summation of x and vv.
#We could implement this approach like this:



In [12]:
a = np.array([1,2,3])
#aa = np.tile(a,1)
#print(aa)
#aa = np.tile(a,2)
#print(aa)
#aa=np.tile(a,[2,1])
#print(aa)
#aa=np.tile(a,[5,2])
#print(aa)
aa = np.tile(a,(3,2))
print(aa)

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


## Using broadcasting

In [16]:
 
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:

a) If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

b) The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

c) The arrays can be broadcast together if they are compatible in all dimensions.

After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

## Applications of broadcasting

In [17]:
## Computer outer product of two vectors v & w
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print(v)
print(w)

[1 2 3]
[4 5]


In [ ]:
#v = 1x3 matrix
#w = 1x2 matrix
#we cannot multiply them
#To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
v - 3x1
w - 1x2
outer product will have a dimension - 3x2


In [18]:
#reshape v
print(np.reshape(v, (3, 1)) * w)



[[ 4  5]
 [ 8 10]
 [12 15]]


In [29]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [28]:
print(x+v)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [6]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 
y = x + vv   
print(y)   


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Array Manipulation Routines 

https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html